import { useEffect, useMemo, useState } from 'react'
import { BellRing, CalendarDays, Check, Clock3, CreditCard, Plus, RefreshCw } from 'lucide-react'
import { useFinance } from '../lib/FinanceContext'
import { formatCurrency, formatDate, formatIDR, initials } from '../lib/format'
import { Badge, Button, Card, Modal, PageHeader } from '../components/ui'
import type { Bill, BudgetCategory } from '../types'

const today=new Date().toISOString().slice(0,10)
export function Bills(){
  const {bills,accounts,refresh,user}=useFinance(),[tab,setTab]=useState<'upcoming'|'paid'|'all'>('upcoming'),[createModal,setCreateModal]=useState(false),[payment,setPayment]=useState<Bill|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[budgetCategories,setBudgetCategories]=useState<BudgetCategory[]>([])
  const canManage=!!user&&['owner','admin','finance'].includes(user.role),paymentAccounts=accounts.filter(account=>['bank','cash','ewallet'].includes(account.kind)),open=bills.filter(bill=>bill.status!=='paid'),attention=open.filter(bill=>bill.status==='due'||bill.status==='overdue'),filtered=useMemo(()=>bills.filter(bill=>tab==='all'||(tab==='paid'?bill.status==='paid':bill.status!=='paid')),[bills,tab])
  const total=open.reduce((sum,bill)=>sum+bill.amount,0),due30=open.filter(bill=>new Date(`${bill.dueDate}T12:00:00`).getTime()<=Date.now()+30*86400000).reduce((sum,bill)=>sum+bill.amount,0)
  useEffect(()=>{const month=new Date().toISOString().slice(0,7);void fetch(`/api/budgets?month=${month}`,{credentials:'include'}).then(response=>response.ok?response.json():null).then(raw=>setBudgetCategories((raw?.categories||[]).map((category:BudgetCategory)=>({...category,plannedAmount:Number(category.plannedAmount),actual:Number(category.actual),pendingAmount:Number(category.pendingAmount),committedAmount:Number(category.committedAmount)}))))},[])
  async function api(url:string,body:unknown){setSaving(true);setError('');try{const response=await fetch(url,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(result.error||'Tagihan belum dapat disimpan');await refresh();return true}catch(e){setError(e instanceof Error?e.message:'Terjadi kesalahan');return false}finally{setSaving(false)}}
  async function createBill(formData:FormData){const reminderDays=String(formData.get('reminderDays')).split(',').map(Number);const ok=await api('/api/bills',{vendor:String(formData.get('vendor')).trim(),description:String(formData.get('description')).trim(),dueDate:String(formData.get('dueDate')),amount:Number(formData.get('amount')),currency:String(formData.get('currency')),recurrence:String(formData.get('recurrence')),owner:String(formData.get('owner')).trim()||undefined,autoRenew:formData.get('autoRenew')==='on',reminderDays});if(ok)setCreateModal(false)}
  async function payBill(formData:FormData){if(!payment)return;const ok=await api(`/api/bills/${payment.id}/pay`,{transactionDate:String(formData.get('transactionDate')),accountId:String(formData.get('accountId')),amount:Number(formData.get('amount')),reference:String(formData.get('reference')).trim()||undefined,budgetCategoryId:String(formData.get('budgetCategoryId'))||undefined,overrideReason:String(formData.get('overrideReason')).trim()||undefined});if(ok)setPayment(null)}
  return <>
    <PageHeader eyebrow="KEWAJIBAN" title="Tagihan & renewal" description="Jadwal renewal dihitung dari data jatuh tempo dan membuat periode berikutnya setelah dibayar." action={canManage?<Button onClick={()=>{setError('');setCreateModal(true)}}><Plus size={16}/> Tambah tagihan</Button>:undefined}/>
    {error&&!createModal&&!payment&&<div className="budget-alert error"><span>{error}</span><button onClick={()=>setError('')}>Tutup</button></div>}
    <div className="mini-stats four"><Card><span>Tagihan mendatang</span><strong>{formatCurrency(total,'IDR')}</strong><small className="warning-text">{open.length} tagihan</small></Card><Card><span>Jatuh tempo 30 hari</span><strong>{formatCurrency(due30,'IDR')}</strong><small>{open.filter(bill=>new Date(bill.dueDate).getTime()<=Date.now()+30*86400000).length} tagihan</small></Card><Card><span>Biaya berulang</span><strong>{formatCurrency(open.filter(bill=>bill.recurrence!=='Sekali').reduce((sum,bill)=>sum+bill.amount,0),'IDR')}</strong><small>{open.filter(bill=>bill.recurrence!=='Sekali').length} layanan aktif</small></Card><Card><span>Sudah dibayar</span><strong className="positive">{formatCurrency(bills.filter(bill=>bill.status==='paid').reduce((sum,bill)=>sum+bill.amount,0),'IDR')}</strong><small>{bills.filter(bill=>bill.status==='paid').length} pembayaran</small></Card></div>
    {attention.length>0&&<Card className="notice-card"><BellRing size={20}/><div><strong>{attention.length} layanan memerlukan perhatian</strong><span>{attention.filter(bill=>bill.status==='overdue').length} terlambat dan {attention.filter(bill=>bill.status==='due').length} segera jatuh tempo.</span></div><button onClick={()=>setTab('upcoming')}>Tinjau sekarang</button></Card>}
    <Card className="data-card bills-table"><div className="tab-bar"><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Akan datang <em>{open.length}</em></button><button className={tab==='paid'?'active':''} onClick={()=>setTab('paid')}>Sudah dibayar</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Semua layanan</button></div><div className="table-scroll"><table><thead><tr><th>Vendor & layanan</th><th>Jatuh tempo</th><th>Siklus</th><th>PIC</th><th>Renewal</th><th>Status</th><th className="align-right">Nominal</th><th className="align-right">Tindakan</th></tr></thead><tbody>{filtered.map((bill,index)=><tr key={bill.id}><td><span className={`vendor-avatar vendor-${index%4}`}>{initials(bill.vendor)}</span><span><strong>{bill.vendor}</strong><small>{bill.description}</small></span></td><td><span className="date-cell"><CalendarDays size={15}/>{formatDate(bill.dueDate)}</span></td><td>{bill.recurrence}</td><td>{bill.owner?<span className="owner-chip">{bill.owner[0]}<em>{bill.owner}</em></span>:'—'}</td><td>{bill.autoRenew?<Badge tone="info"><RefreshCw size={12}/> Otomatis</Badge>:<Badge>Manual</Badge>}</td><td><Badge tone={bill.status==='paid'?'success':bill.status==='overdue'?'danger':bill.status==='due'?'warning':'neutral'}>{bill.status==='paid'?<><Check size={12}/> Dibayar</>:bill.status==='overdue'?<><Clock3 size={12}/> Terlambat</>:bill.status==='due'?<><Clock3 size={12}/> Segera</>:'Terjadwal'}</Badge></td><td className="align-right amount">{formatCurrency(bill.amount,bill.currency)}</td><td className="align-right"><div className="row-actions">{canManage&&bill.status!=='paid'?<button className="approve" onClick={()=>{setError('');setPayment(bill)}}><CreditCard size={13}/> Bayar</button>:<span>—</span>}</div></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="dashboard-empty"><CalendarDays size={25}/><strong>Belum ada tagihan</strong><span>Tambahkan layanan agar pengingat renewal muncul otomatis.</span></div>}</Card>
    {createModal&&<Modal title="Tambah tagihan atau renewal" description="Atur jadwal, siklus, dan pengingat internal." onClose={()=>{setCreateModal(false);setError('')}}><form className="form-grid" action={createBill}>{error&&<div className="auth-error span-2">{error}</div>}<label>Vendor<input name="vendor" required minLength={2} maxLength={120}/></label><label>Jatuh tempo<input name="dueDate" type="date" required/></label><label className="span-2">Layanan/deskripsi<input name="description" required minLength={3} maxLength={200}/></label><label>Nominal<input name="amount" type="number" min="1" step="1" required/></label><label>Mata uang<select name="currency"><option value="IDR">IDR</option><option value="USD">USD</option></select></label><label>Siklus<select name="recurrence"><option value="monthly">Bulanan</option><option value="yearly">Tahunan</option><option value="once">Sekali</option></select></label><label>PIC<input name="owner" maxLength={100}/></label><label>Pengingat<select name="reminderDays" defaultValue="14,7,1"><option value="14,7,1">14, 7, dan 1 hari</option><option value="7,3,1">7, 3, dan 1 hari</option><option value="30,14,7">30, 14, dan 7 hari</option></select></label><label className="checkbox-label"><input name="autoRenew" type="checkbox"/> Renewal otomatis oleh vendor</label><div className="form-note span-2">Pengingat muncul berdasarkan tanggal jatuh tempo. Pembayaran tetap harus dikonfirmasi Finance.</div><div className="modal-actions span-2"><Button variant="secondary" onClick={()=>setCreateModal(false)}>Batal</Button><Button type="submit" disabled={saving}>{saving?'Menyimpan…':'Simpan tagihan'}</Button></div></form></Modal>}
    {payment&&<Modal title={`Bayar ${payment.vendor}`} description={`${payment.description} · ${formatIDR(payment.amount)}`} onClose={()=>{setPayment(null);setError('')}}><form className="form-grid" action={payBill}>{error&&<div className="auth-error span-2">{error}</div>}<label>Tanggal pembayaran<input name="transactionDate" type="date" defaultValue={today} required/></label><label>Nominal aktual<input name="amount" type="number" min="1" step="1" defaultValue={payment.amount} required/></label><label className="span-2">Rekening<select name="accountId" defaultValue="" required><option value="" disabled>Pilih rekening</option>{paymentAccounts.map(account=><option value={account.id} key={account.id}>{account.name} — {formatIDR(account.balance)}</option>)}</select></label><label className="span-2">Pos RAB <span className="optional-label">Opsional</span><select name="budgetCategoryId"><option value="">Di luar RAB</option>{budgetCategories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Referensi bank<input name="reference" maxLength={100}/></label><label>Alasan override RAB <span className="optional-label">Jika diperlukan</span><input name="overrideReason" maxLength={500}/></label><div className="form-note span-2">Tagihan berulang otomatis menghasilkan jadwal periode berikutnya setelah pembayaran berhasil.</div><div className="modal-actions span-2"><Button variant="secondary" onClick={()=>setPayment(null)}>Batal</Button><Button type="submit" disabled={saving}>{saving?'Memproses…':'Catat pembayaran'}</Button></div></form></Modal>}
  </>
}
