import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowDownLeft, ArrowRight, ArrowUpRight, BarChart3, CalendarDays, CheckCircle2, CircleAlert, CreditCard, Landmark, Plus, ReceiptText, RefreshCw, ShoppingCart, WalletCards } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useFinance } from '../lib/FinanceContext'
import { formatCurrency, formatDate, formatIDR } from '../lib/format'
import { Badge, Button, Card, PageHeader } from '../components/ui'
import type { BudgetCategory } from '../types'

type AttentionItem={id:string;title:string;description:string;count:number;amount?:number;tone:'danger'|'warning'|'info'|'neutral';path:string;action:string;icon:React.ReactNode}
function StatCard({icon,label,value,note,tone}:{icon:React.ReactNode;label:string;value:string;note:React.ReactNode;tone:string}){return <Card className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small>{note}</small></div></Card>}

export function Dashboard(){
  const {accounts,bills,deposits,transactions,purchaseRequests,user,settings}=useFinance(),navigate=useNavigate(),currentMonth=new Date().toISOString().slice(0,7)
  const [report,setReport]=useState<{income:number;expense:number;cashflow:Array<{month:string;income:number;expense:number}>}>({income:0,expense:0,cashflow:[]}),[budget,setBudget]=useState<{exists:boolean;categories:BudgetCategory[]}>({exists:false,categories:[]})
  useEffect(()=>{void Promise.all([fetch(`/api/reports?month=${currentMonth}`,{credentials:'include'}),fetch(`/api/budgets?month=${currentMonth}`,{credentials:'include'})]).then(async([reportResponse,budgetResponse])=>{if(reportResponse.ok){const raw=await reportResponse.json();setReport({income:Number(raw.summary?.income||0),expense:Number(raw.summary?.expense||0),cashflow:(raw.cashflow||[]).map((item:{month:string;income:string|number;expense:string|number})=>({month:new Intl.DateTimeFormat('id-ID',{month:'short'}).format(new Date(`${item.month}-01T12:00:00`)),income:Number(item.income),expense:Number(item.expense)}))})}if(budgetResponse.ok){const raw=await budgetResponse.json();setBudget({exists:!!raw.budget,categories:(raw.categories||[]).map((item:BudgetCategory)=>({...item,plannedAmount:Number(item.plannedAmount),actual:Number(item.actual),pendingAmount:Number(item.pendingAmount),committedAmount:Number(item.committedAmount)}))})}})},[currentMonth])
  // eslint-disable-next-line react-hooks/exhaustive-deps -- switches intentionally create role-scoped queues
  const canFinance=!!user&&['owner','admin','finance'].includes(user.role),cashAccounts=accounts.filter(account=>['bank','cash','ewallet'].includes(account.kind)),unpaidBills=bills.filter(bill=>bill.status!=='paid'),dueBills=settings.notifyBills?unpaidBills.filter(bill=>bill.status==='due'||bill.status==='overdue'):[],unreconciled=settings.notifyReconciliation?cashAccounts.filter(account=>!account.reconciled):[],lowDeposits=settings.notifyLowDeposit?deposits.filter(deposit=>deposit.balance<deposit.lowBalanceThreshold):[],submitted=settings.notifyPurchaseApproval?purchaseRequests.filter(request=>request.status==='submitted'):[],approved=settings.notifyPurchaseApproval?purchaseRequests.filter(request=>request.status==='approved'):[],myOpen=purchaseRequests.filter(request=>request.requestedById===user?.userId&&!['received','rejected'].includes(request.status))
  const cashBalance=cashAccounts.reduce((sum,account)=>sum+account.balance,0),depositBalance=deposits.reduce((sum,deposit)=>sum+deposit.balance,0),netCash=report.income-report.expense
  const budgetSummary=useMemo(()=>budget.categories.reduce((result,category)=>({planned:result.planned+category.plannedAmount,used:result.used+category.actual+category.committedAmount,pending:result.pending+category.pendingAmount,warnings:result.warnings+(category.plannedAmount>0&&(category.actual+category.committedAmount)/category.plannedAmount>=.9?1:0)}),{planned:0,used:0,pending:0,warnings:0}),[budget.categories])
  const attention=useMemo(()=>{const items:AttentionItem[]=[];if(canFinance&&submitted.length)items.push({id:'approval',title:'Pengajuan menunggu persetujuan',description:'Periksa kebutuhan dan ketersediaan RAB.',count:submitted.length,amount:submitted.reduce((sum,item)=>sum+item.amount,0),tone:'warning',path:'/pengajuan-belanja',action:'Tinjau',icon:<ShoppingCart size={19}/>});if(canFinance&&approved.length)items.push({id:'payment',title:'Pengajuan siap dibayar',description:'Sudah disetujui dan mencadangkan anggaran.',count:approved.length,amount:approved.reduce((sum,item)=>sum+item.amount,0),tone:'info',path:'/pengajuan-belanja',action:'Bayar',icon:<CreditCard size={19}/>});if(!canFinance&&myOpen.length)items.push({id:'mine',title:'Pengajuan saya masih berjalan',description:'Pantau status sampai barang atau jasa diterima.',count:myOpen.length,tone:'info',path:'/pengajuan-belanja',action:'Pantau',icon:<ShoppingCart size={19}/>});if(canFinance&&dueBills.length)items.push({id:'bills',title:'Tagihan perlu dibayar',description:'Tagihan segera jatuh tempo atau sudah terlambat.',count:dueBills.length,amount:dueBills.reduce((sum,item)=>sum+item.amount,0),tone:dueBills.some(item=>item.status==='overdue')?'danger':'warning',path:'/tagihan',action:'Buka tagihan',icon:<CalendarDays size={19}/>});if(canFinance&&unreconciled.length)items.push({id:'reconcile',title:'Rekening belum direkonsiliasi',description:'Cocokkan saldo buku dengan mutasi bank atau kas.',count:unreconciled.length,tone:'warning',path:'/rekening',action:'Rekonsiliasi',icon:<RefreshCw size={19}/>});if(canFinance&&lowDeposits.length)items.push({id:'deposit',title:'Saldo deposit rendah',description:'Periksa kebutuhan top-up sebelum layanan berhenti.',count:lowDeposits.length,amount:lowDeposits.reduce((sum,item)=>sum+item.balance,0),tone:'danger',path:'/deposit',action:'Periksa',icon:<AlertTriangle size={19}/>});if(canFinance&&budgetSummary.warnings)items.push({id:'budget',title:'Pos RAB mendekati batas',description:'Realisasi dan alokasi sudah mencapai sedikitnya 90%.',count:budgetSummary.warnings,tone:'warning',path:'/anggaran',action:'Lihat RAB',icon:<CircleAlert size={19}/>});return items},[approved,budgetSummary.warnings,canFinance,dueBills,lowDeposits,myOpen,submitted,unreconciled])
  if(canFinance&&settings.minimumCashBalance>0&&cashBalance<settings.minimumCashBalance)attention.unshift({id:'cash',title:'Dana tersedia di bawah batas aman',description:`Saldo likuid lebih rendah dari batas ${formatIDR(settings.minimumCashBalance)}.`,count:1,amount:cashBalance,tone:'danger',path:'/rekening',action:'Periksa saldo',icon:<Landmark size={19}/>})
  const primaryAttention=attention.slice(0,5),hasCashflow=report.cashflow.some(point=>point.income||point.expense),budgetPercent=budgetSummary.planned?Math.round(budgetSummary.used/budgetSummary.planned*100):0
  return <>
    <PageHeader eyebrow={new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date())} title={`Selamat datang, ${user?.fullName||'Tim Finance'}`} description={canFinance?'Selesaikan pekerjaan prioritas dan pantau kondisi kas hari ini.':'Ajukan kebutuhan dan pantau prosesnya dari satu tempat.'} action={<>{canFinance&&<Button variant="secondary" onClick={()=>navigate('/transaksi?buat=expense')}><ArrowUpRight size={16}/> Pengeluaran</Button>}<Button onClick={()=>navigate(canFinance?'/transaksi?buat=income':'/pengajuan-belanja?buat=1')}><Plus size={16}/>{canFinance?'Dana masuk':'Buat pengajuan'}</Button></>}/>

    <div className="stats-grid dashboard-kpis"><StatCard icon={<Landmark size={20}/>} label="Dana tersedia" value={formatIDR(cashBalance)} note={`${cashAccounts.length} rekening likuid`} tone="teal"/><StatCard icon={<ArrowDownLeft size={20}/>} label="Pendapatan bulan ini" value={formatIDR(report.income)} note="Jurnal posted bersih" tone="teal"/><StatCard icon={<ReceiptText size={20}/>} label="Pengeluaran bulan ini" value={formatIDR(report.expense)} note="Setelah koreksi" tone="purple"/><StatCard icon={<BarChart3 size={20}/>} label="Arus kas bersih" value={formatIDR(netCash)} note={<span className={netCash>=0?'positive':'negative'}>{netCash>=0?'Surplus':'Defisit'} bulan berjalan</span>} tone="amber"/><StatCard icon={<WalletCards size={20}/>} label="Saldo deposit" value={formatIDR(depositBalance)} note={`${lowDeposits.length} saldo rendah`} tone="orange"/></div>

    <section className="daily-workspace" id="perlu-tindakan">
      <Card className="attention-card"><div className="card-heading"><div><h2>Perlu tindakan</h2><p>Urutan pekerjaan berdasarkan kondisi terbaru</p></div><Badge tone={attention.length?'warning':'success'}>{attention.length?`${attention.length} prioritas`:'Semua aman'}</Badge></div><div className="attention-list">{primaryAttention.map(item=><button className="attention-row" key={item.id} onClick={()=>navigate(item.path)}><span className={`attention-icon ${item.tone}`}>{item.icon}</span><span className="attention-copy"><strong>{item.title}</strong><small>{item.description}</small></span><span className="attention-value"><strong>{item.amount!==undefined?formatIDR(item.amount):`${item.count} item`}</strong><small>{item.count} perlu ditangani</small></span><span className="attention-action">{item.action}<ArrowRight size={14}/></span></button>)}{!attention.length&&<div className="attention-empty"><CheckCircle2 size={28}/><div><strong>Tidak ada pekerjaan mendesak</strong><span>Saldo, tagihan, pengajuan, dan anggaran tidak memerlukan tindakan saat ini.</span></div></div>}</div>{attention.length>5&&<button className="full-link" onClick={()=>navigate('/pengajuan-belanja')}>Lihat seluruh prioritas <ArrowRight size={15}/></button>}</Card>
      <div className="dashboard-side-stack"><Card className="quick-actions-card"><div className="card-heading"><div><h2>Tindakan cepat</h2><p>Pencatatan yang paling sering digunakan</p></div></div><div className="quick-action-grid">{canFinance&&<button onClick={()=>navigate('/transaksi?buat=income')}><span className="quick-icon income"><ArrowDownLeft size={19}/></span><strong>Dana masuk</strong><small>Pendapatan atau modal</small></button>}{canFinance&&<button onClick={()=>navigate('/transaksi?buat=expense')}><span className="quick-icon expense"><ArrowUpRight size={19}/></span><strong>Pengeluaran</strong><small>Biaya operasional</small></button>}<button onClick={()=>navigate('/pengajuan-belanja?buat=1')}><span className="quick-icon request"><ShoppingCart size={19}/></span><strong>Pengajuan</strong><small>Kebutuhan kantor</small></button>{canFinance&&<button onClick={()=>navigate('/rekening')}><span className="quick-icon reconcile"><RefreshCw size={19}/></span><strong>Rekonsiliasi</strong><small>Cocokkan saldo</small></button>}</div></Card><Card className="budget-snapshot"><div className="card-heading"><div><h2>RAB bulan ini</h2><p>Realisasi dan alokasi</p></div><button onClick={()=>navigate('/anggaran')}>Detail <ArrowRight size={13}/></button></div>{budget.exists?<><div className="budget-snapshot-total"><strong>{formatIDR(budgetSummary.used)}</strong><span>dari {formatIDR(budgetSummary.planned)}</span><b>{budgetPercent}%</b></div><div className={`budget-snapshot-progress ${budgetPercent>=100?'danger':budgetPercent>=90?'warning':''}`}><span style={{width:`${Math.min(100,budgetPercent)}%`}}/></div><div className="budget-snapshot-meta"><span>Sisa <strong>{formatIDR(budgetSummary.planned-budgetSummary.used)}</strong></span><span>Menunggu <strong>{formatIDR(budgetSummary.pending)}</strong></span></div></>:<div className="compact-empty"><CircleAlert size={21}/><span><strong>RAB belum dibuat</strong><small>Susun batas pengeluaran bulan ini.</small></span><button onClick={()=>navigate('/anggaran')}>Buat RAB</button></div>}</Card></div>
    </section>

    <div className="dashboard-grid"><Card className="chart-card"><div className="card-heading"><div><h2>Arus kas</h2><p>Pendapatan dan pengeluaran 6 bulan terakhir</p></div><button onClick={()=>navigate('/laporan')}>Laporan <ArrowRight size={13}/></button></div><div className="chart-summary"><div><span>Pendapatan bulan ini</span><strong>{formatIDR(report.income)}</strong><small className="positive"><ArrowUpRight size={13}/> Tercatat</small></div><div><span>Pengeluaran bulan ini</span><strong>{formatIDR(report.expense)}</strong><small className="negative"><ArrowDownLeft size={13}/> Tercatat</small></div></div><div className="chart-wrap">{hasCashflow?<ResponsiveContainer width="100%" height="100%"><AreaChart data={report.cashflow} margin={{top:8,right:4,left:-16,bottom:0}}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f7168" stopOpacity=".24"/><stop offset="100%" stopColor="#2f7168" stopOpacity="0"/></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d89b50" stopOpacity=".2"/><stop offset="100%" stopColor="#d89b50" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#e9eeec" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={value=>`${value/1000000}jt`}/><Tooltip formatter={value=>formatIDR(Number(value))}/><Area type="monotone" dataKey="income" name="Pendapatan" stroke="#2f7168" strokeWidth={2.5} fill="url(#incomeFill)"/><Area type="monotone" dataKey="expense" name="Pengeluaran" stroke="#d89b50" strokeWidth={2.5} fill="url(#expenseFill)"/></AreaChart></ResponsiveContainer>:<div className="dashboard-empty chart-empty"><BarChart3 size={28}/><strong>Belum ada arus kas</strong><span>Grafik terisi setelah transaksi pertama diposting.</span></div>}</div></Card>
      <Card className="upcoming-card"><div className="card-heading"><div><h2>Tagihan terdekat</h2><p>Urut berdasarkan jatuh tempo</p></div><button onClick={()=>navigate('/tagihan')}>Lihat semua</button></div><div className="bill-list">{unpaidBills.slice(0,4).map((bill,index)=><button className="bill-row dashboard-clickable" key={bill.id} onClick={()=>navigate('/tagihan')}><span className={`vendor-avatar vendor-${index%4}`}>{bill.vendor.slice(0,2).toUpperCase()}</span><span className="bill-info"><strong>{bill.vendor}</strong><span>{bill.description}</span></span><span className="bill-amount"><strong>{formatCurrency(bill.amount,bill.currency)}</strong><Badge tone={bill.status==='overdue'?'danger':bill.status==='due'?'warning':'neutral'}>{formatDate(bill.dueDate)}</Badge></span></button>)}{!unpaidBills.length&&<div className="dashboard-empty"><CalendarDays size={24}/><strong>Belum ada tagihan</strong><span>Jadwal renewal akan tampil di sini.</span></div>}</div><button className="full-link" onClick={()=>navigate('/tagihan')}>Kelola tagihan & renewal <ArrowRight size={15}/></button></Card></div>

    <div className="dashboard-grid lower-grid"><Card className="account-summary-card"><div className="card-heading"><div><h2>Rekening & saldo</h2><p>Posisi dana perusahaan</p></div><button onClick={()=>navigate('/rekening')}>Lihat semua</button></div><div className="account-list">{cashAccounts.slice(0,4).map(account=><button className="account-row dashboard-clickable" key={account.id} onClick={()=>navigate('/rekening')}><span className="account-color" style={{background:account.color}}><Landmark size={17}/></span><span className="account-info"><strong>{account.name}</strong><small>{account.maskedNumber||account.institution}</small></span><span className="account-value"><strong>{formatCurrency(account.balance,account.currency)}</strong><span className={account.reconciled?'matched':'unmatched'}>{account.reconciled?<CheckCircle2 size={13}/>:<CircleAlert size={13}/>} {account.reconciled?'Cocok':'Periksa'}</span></span></button>)}{!cashAccounts.length&&<div className="dashboard-empty"><Landmark size={24}/><strong>Belum ada rekening</strong><span>Tambahkan rekening untuk memulai.</span></div>}</div></Card><Card className="deposit-summary-card"><div className="card-heading"><div><h2>Saldo deposit</h2><p>Ketahanan layanan prabayar</p></div><button onClick={()=>navigate('/deposit')}>Lihat semua</button></div><div className="deposit-list">{deposits.slice(0,4).map(deposit=>{const days=deposit.dailyAverage>0?Math.floor(deposit.balance/deposit.dailyAverage):null,progress=Math.min(100,deposit.balance/(deposit.monthlyUsage||1)*100);return <button className="deposit-row dashboard-clickable" key={deposit.id} onClick={()=>navigate('/deposit')}><span className="deposit-top"><i className="platform-dot" style={{background:deposit.color}}/><span><strong>{deposit.platform}</strong><small>{deposit.accountName}</small></span><span><strong>{formatIDR(deposit.balance)}</strong><small className={days!==null&&days<14?'low-days':''}>{days===null?'Belum ada pola':`± ${days} hari`}</small></span></span><span className="progress"><i style={{width:`${progress}%`,background:deposit.color}}/></span></button>})}{!deposits.length&&<div className="dashboard-empty"><WalletCards size={24}/><strong>Belum ada deposit</strong><span>Deposit platform akan tampil di sini.</span></div>}</div></Card></div>

    <Card className="recent-card"><div className="card-heading"><div><h2>Aktivitas terbaru</h2><p>Seluruh perubahan dana terakhir</p></div><button onClick={()=>navigate('/transaksi')}>Lihat semua transaksi <ArrowRight size={14}/></button></div><div className="table-scroll"><table><thead><tr><th>Transaksi</th><th>Tanggal</th><th>Kategori</th><th>Rekening</th><th>Status</th><th className="align-right">Nominal</th></tr></thead><tbody>{transactions.slice(0,5).map(transaction=><tr key={transaction.id}><td><div className={`trx-icon ${transaction.amount>0?'in':'out'}`}>{transaction.amount>0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</div><span><strong>{transaction.description}</strong><small>{transaction.reference||'Tanpa referensi'}</small></span></td><td>{formatDate(transaction.date)}</td><td>{transaction.category}</td><td>{transaction.account}</td><td><Badge tone={transaction.status==='posted'?'success':'warning'}>{transaction.status==='posted'?'Selesai':'Pending'}</Badge></td><td className={`align-right amount ${transaction.amount>0?'positive':''}`}>{transaction.amount>0?'+':''}{formatIDR(transaction.amount)}</td></tr>)}</tbody></table></div>{!transactions.length&&<div className="dashboard-empty table-empty"><ReceiptText size={24}/><strong>Belum ada transaksi</strong><span>Aktivitas keuangan terbaru akan tampil di sini.</span></div>}</Card>
  </>
}
