import { useCallback, useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, FileSpreadsheet, PieChart, TrendingUp } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart as RePieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { formatIDR } from '../lib/format'
import { Button, Card, PageHeader } from '../components/ui'

type ReportData={summary:{income:number;expense:number;depositBalance:number};categories:Array<{name:string;value:number;color:string}>;cashflow:Array<{month:string;income:number;expense:number}>}
const colors=['#2f7168','#d89b50','#766a8b','#748c87','#c9b38f','#4f78a5','#b85d55']
const initialMonth=new Date().toISOString().slice(0,7)
function monthLabel(month:string){return new Intl.DateTimeFormat('id-ID',{month:'short'}).format(new Date(`${month}-01T12:00:00`))}

export function Reports(){
  const [month,setMonth]=useState(initialMonth),[loading,setLoading]=useState(true),[error,setError]=useState(''),[data,setData]=useState<ReportData>({summary:{income:0,expense:0,depositBalance:0},categories:[],cashflow:[]})
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/reports?month=${month}`,{credentials:'include'});const raw=await response.json();if(!response.ok)throw new Error(raw.error||'Laporan belum dapat dimuat');setData({summary:{income:Number(raw.summary?.income||0),expense:Number(raw.summary?.expense||0),depositBalance:Number(raw.summary?.depositBalance||0)},categories:(raw.categories||[]).map((item:{name:string;value:string|number},index:number)=>({name:item.name,value:Number(item.value),color:colors[index%colors.length]})),cashflow:(raw.cashflow||[]).map((item:{month:string;income:string|number;expense:string|number})=>({month:monthLabel(item.month),income:Number(item.income),expense:Number(item.expense)}))})}catch(e){setError(e instanceof Error?e.message:'Terjadi kesalahan')}finally{setLoading(false)}},[month]);useEffect(()=>{void load()},[load])
  const net=data.summary.income-data.summary.expense,margin=data.summary.income?Math.round(net/data.summary.income*1000)/10:0
  const csv=useMemo(()=>[['Kategori','Nominal'],...data.categories.map(item=>[item.name,String(item.value)]),[],['Pendapatan',String(data.summary.income)],['Pengeluaran',String(data.summary.expense)],['Arus kas bersih',String(net)],['Saldo deposit',String(data.summary.depositBalance)]].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n'),[data,net])
  function download(){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:'text/csv;charset=utf-8'}));link.download=`emisell-finance-${month}.csv`;link.click();URL.revokeObjectURL(link.href)}
  return <>
    <PageHeader eyebrow="INSIGHT" title="Laporan keuangan" description="Seluruh angka dihitung dari jurnal posted, termasuk koreksi reversal." action={<Button onClick={download}><Download size={16}/> Ekspor CSV</Button>}/>
    {error&&<div className="budget-alert error"><span>{error}</span><button onClick={()=>setError('')}>Tutup</button></div>}
    <div className="report-period"><span>Periode laporan</span><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/><small>{loading?'Menghitung laporan…':'Data jurnal terbaru'}</small></div>
    <div className="mini-stats four report-stats"><Card><TrendingUp/><span>Pendapatan</span><strong>{formatIDR(data.summary.income)}</strong><small>Jurnal dana masuk bersih</small></Card><Card><BarChart3/><span>Pengeluaran</span><strong>{formatIDR(data.summary.expense)}</strong><small>Setelah reversal</small></Card><Card><PieChart/><span>Arus kas bersih</span><strong className={net>=0?'positive':'negative'}>{formatIDR(net)}</strong><small>Margin {margin}%</small></Card><Card><FileSpreadsheet/><span>Aset deposit</span><strong>{formatIDR(data.summary.depositBalance)}</strong><small>Saldo buku platform</small></Card></div>
    <div className="dashboard-grid report-grid"><Card><div className="card-heading"><div><h2>Tren arus kas</h2><p>6 bulan terakhir</p></div></div><div className="report-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.cashflow}><CartesianGrid stroke="#e9eeec" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={value=>`${value/1000000}jt`}/><Tooltip formatter={value=>formatIDR(Number(value))}/><Bar dataKey="income" name="Pendapatan" fill="#2f7168" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Pengeluaran" fill="#d89b50" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card><div className="card-heading"><div><h2>Pengeluaran per kategori</h2><p>Realisasi periode terpilih</p></div></div>{data.categories.length?<div className="pie-layout"><div className="pie-chart"><ResponsiveContainer width="100%" height="100%"><RePieChart><Pie data={data.categories} dataKey="value" innerRadius={48} outerRadius={72} paddingAngle={3}>{data.categories.map(category=><Cell key={category.name} fill={category.color}/>)}</Pie><Tooltip formatter={value=>formatIDR(Number(value))}/></RePieChart></ResponsiveContainer><span><strong>{formatIDR(data.summary.expense,true)}</strong><small>Total</small></span></div><div className="legend">{data.categories.map(category=><div key={category.name}><i style={{background:category.color}}/><span>{category.name}</span><strong>{formatIDR(category.value,true)}</strong></div>)}</div></div>:<div className="dashboard-empty"><FileSpreadsheet size={25}/><strong>Belum ada pengeluaran</strong><span>Kategori muncul setelah transaksi pengeluaran diposting.</span></div>}</Card></div>
    <Card className="export-card"><div><FileSpreadsheet size={25}/><span><strong>Laporan dapat diaudit</strong><small>Angka bersumber dari jurnal posted dan tidak menggunakan data contoh.</small></span></div><Button variant="secondary" onClick={download}><Download size={15}/> Unduh CSV</Button></Card>
  </>
}
