import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { KeyRound, LoaderCircle, LockKeyhole, ShieldCheck, WalletCards } from 'lucide-react'

type SessionState={authenticated:boolean;setupRequired:boolean;user?:{fullName:string}}
async function request(url:string,body?:unknown){const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,credentials:'include',body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Permintaan gagal');return data}

export function AuthGate({children}:{children:ReactNode}){
  const [state,setState]=useState<SessionState|null>(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false)
  useEffect(()=>{request('/api/auth/session').then(setState).catch(()=>setError('Server database belum dapat dihubungi.'))},[])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setError('');const f=new FormData(event.currentTarget);try{const setup=state?.setupRequired;await request(setup?'/api/auth/setup':'/api/auth/login',setup?{organizationName:f.get('organizationName'),fullName:f.get('fullName'),email:f.get('email'),password:f.get('password')}:{email:f.get('email'),password:f.get('password')});setState(await request('/api/auth/session'))}catch(e){setError(e instanceof Error?e.message:'Tidak dapat masuk')}finally{setSubmitting(false)}}
  if(!state&&!error)return <div className="auth-loading"><LoaderCircle className="spin"/><span>Memverifikasi sesi aman…</span></div>
  if(state?.authenticated)return children
  const setup=state?.setupRequired
  return <main className="auth-page"><section className="auth-panel"><div className="auth-brand"><span><WalletCards size={24}/></span><div><strong>Emisell Finance</strong><small>Finance workspace</small></div></div><div className="auth-copy"><span className="auth-lock"><LockKeyhole size={20}/></span><h1>{setup?'Siapkan workspace':'Masuk ke workspace'}</h1><p>{setup?'Buat akun Owner pertama untuk perusahaan Anda.':'Gunakan akun yang telah diberikan oleh Owner.'}</p></div><form onSubmit={submit} className="auth-form">{setup&&<><label>Nama perusahaan<input name="organizationName" required minLength={2} defaultValue="Emisell"/></label><label>Nama Owner<input name="fullName" required minLength={2}/></label></>}<label>Email perusahaan<input name="email" type="email" required autoComplete="username"/></label><label>Kata sandi<input name="password" type="password" minLength={12} required autoComplete={setup?'new-password':'current-password'} placeholder="Minimal 12 karakter"/></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button disabled={submitting}>{submitting?<LoaderCircle className="spin" size={17}/>:<KeyRound size={17}/>} {setup?'Buat workspace':'Masuk dengan aman'}</button></form><div className="auth-security"><ShieldCheck size={17}/><span><strong>Akses terbatas</strong><small>Cookie HttpOnly, rate limit, audit log, dan database terisolasi.</small></span></div></section><aside className="auth-aside"><div><span>EMISELL FINANCE</span><h2>Keuangan perusahaan, rapi dan terkendali.</h2><p>Kelola rekening, deposit, kredit, pengajuan, dan renewal dalam satu tempat.</p></div></aside></main>
}
