create extension if not exists pgcrypto;
create table organizations(id uuid primary key default gen_random_uuid(),name varchar(120) not null,base_currency char(3) not null default 'IDR',created_at timestamptz not null default now());
create table users(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),email varchar(254) not null,full_name varchar(100) not null,password_hash text not null,role varchar(20) not null check(role in('owner','finance','staff')),active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,email));
create unique index users_email_lower_idx on users(lower(email));
create table sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,token_hash char(64) not null unique,expires_at timestamptz not null,created_at timestamptz not null default now(),last_seen_at timestamptz not null default now());
create index sessions_expiry_idx on sessions(expires_at);
create table accounts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),name varchar(100) not null,institution varchar(100),kind varchar(20) not null check(kind in('bank','cash','credit','ewallet','deposit','clearing')),masked_number varchar(20),currency char(3) not null default 'IDR',opening_balance numeric(20,2) not null default 0,credit_limit numeric(20,2),low_balance_threshold numeric(20,2),color char(7) not null default '#225c55',active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,name));
create table transactions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),transaction_date date not null,kind varchar(30) not null,status varchar(12) not null default 'draft' check(status in('draft','pending','posted','reversed')),description varchar(240) not null,category varchar(80) not null,reference varchar(100),created_by uuid not null references users(id),posted_by uuid references users(id),posted_at timestamptz,created_at timestamptz not null default now());
create table transaction_entries(id uuid primary key default gen_random_uuid(),transaction_id uuid not null references transactions(id),account_id uuid not null references accounts(id),amount numeric(20,2) not null check(amount<>0),created_at timestamptz not null default now());
create index transaction_entries_account_idx on transaction_entries(account_id);
create table bills(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),vendor varchar(120) not null,description varchar(200) not null,due_date date not null,amount numeric(20,2) not null check(amount>0),currency char(3) not null default 'IDR',recurrence varchar(20) not null default 'monthly',status varchar(20) not null default 'upcoming',owner_name varchar(100),auto_renew boolean not null default false,created_at timestamptz not null default now());
create table purchase_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),request_number varchar(30) not null,requested_by uuid not null references users(id),department varchar(80) not null,title varchar(120) not null,purpose varchar(500) not null,urgency varchar(10) not null default 'normal',status varchar(20) not null default 'submitted',vendor varchar(120),estimated_total numeric(20,2) not null default 0,created_at timestamptz not null default now(),unique(organization_id,request_number));
create table purchase_request_items(id uuid primary key default gen_random_uuid(),purchase_request_id uuid not null references purchase_requests(id) on delete cascade,item_name varchar(160) not null,quantity numeric(12,2) not null check(quantity>0),unit_price numeric(20,2) not null check(unit_price>=0));
create table purchase_events(id bigserial primary key,purchase_request_id uuid not null references purchase_requests(id),from_status varchar(20),to_status varchar(20) not null,actor_id uuid not null references users(id),note varchar(500),created_at timestamptz not null default now());
create table audit_logs(id bigserial primary key,organization_id uuid not null references organizations(id),actor_id uuid references users(id),entity varchar(50) not null,entity_id uuid not null,action varchar(30) not null,data jsonb,created_at timestamptz not null default now());

create or replace function protect_posted_transaction() returns trigger language plpgsql as $$ begin if old.status in('posted','reversed') then raise exception 'Posted transactions are immutable'; end if; return new; end $$;
create trigger transactions_immutable before update or delete on transactions for each row execute function protect_posted_transaction();
